using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QDocument = QuestPDF.Fluent.Document;
using TravelAgency.Core.Patterns.Bridge.Models;

namespace TravelAgency.Core.Patterns.Bridge.Exporters
{
    public class PdfReportExporter : IReportExporter
    {
        public string FileExtension => ".pdf";

        public string Export(ReportDocument document, string outputPath)
        {
            QDocument.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(25);

                    page.Header().Column(column =>
                    {
                        column.Item().Text(document.Title).Bold().FontSize(18);
                        column.Item().Text($"Generated by: {document.GeneratedBy}");
                        column.Item().Text($"Generated at: {document.GeneratedAt:dd.MM.yyyy HH:mm}");
                        column.Item().Text(document.Summary).Italic();
                    });

                    page.Content().PaddingVertical(10).Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(2); // Client
                            columns.RelativeColumn(2); // Package
                            columns.RelativeColumn(2); // Destination
                            columns.RelativeColumn(1); // Status
                            columns.RelativeColumn(1); // Booking Date
                            columns.RelativeColumn(2); // Travel Period
                            columns.RelativeColumn(1); // Price
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(ApplyCellStyle).Text("Client").Bold();
                            header.Cell().Element(ApplyCellStyle).Text("Package").Bold();
                            header.Cell().Element(ApplyCellStyle).Text("Destination").Bold();
                            header.Cell().Element(ApplyCellStyle).Text("Status").Bold();
                            header.Cell().Element(ApplyCellStyle).Text("Booking Date").Bold();
                            header.Cell().Element(ApplyCellStyle).Text("Travel Period").Bold();
                            header.Cell().Element(ApplyCellStyle).Text("Price").Bold();
                        });

                        foreach (var row in document.Rows)
                        {
                            table.Cell().Element(ApplyCellStyle).Text(row.ClientName);
                            table.Cell().Element(ApplyCellStyle).Text(row.PackageName);
                            table.Cell().Element(ApplyCellStyle).Text(row.Destination);
                            table.Cell().Element(ApplyCellStyle).Text(row.Status);
                            table.Cell().Element(ApplyCellStyle).Text(row.BookingDate);
                            table.Cell().Element(ApplyCellStyle).Text(row.TravelPeriod);
                            table.Cell().Element(ApplyCellStyle).Text(row.Price);
                        }
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text("TravelAgencySystem - Agent Reports");
                });
            }).GeneratePdf(outputPath);

            return outputPath;
        }

        private static IContainer ApplyCellStyle(IContainer container)
        {
            return container
                .Border(1)
                .BorderColor(Colors.Grey.Lighten2)
                .Padding(5);
        }
    }
}