using System.IO;
using System.Text;
using TravelAgency.Core.Patterns.Bridge.Models;

namespace TravelAgency.Core.Patterns.Bridge.Exporters
{
    public class TxtReportExporter : IReportExporter
    {
        public string FileExtension => ".txt";

        public string Export(ReportDocument document, string outputPath)
        {
            var sb = new StringBuilder();

            sb.AppendLine(document.Title);
            sb.AppendLine(new string('=', document.Title.Length));
            sb.AppendLine($"Generated by: {document.GeneratedBy}");
            sb.AppendLine($"Generated at: {document.GeneratedAt:dd.MM.yyyy HH:mm}");
            sb.AppendLine(document.Summary);
            sb.AppendLine();

            foreach (var row in document.Rows)
            {
                sb.AppendLine($"Client: {row.ClientName}");
                sb.AppendLine($"Package: {row.PackageName}");
                sb.AppendLine($"Destination: {row.Destination}");
                sb.AppendLine($"Status: {row.Status}");
                sb.AppendLine($"Booking Date: {row.BookingDate}");
                sb.AppendLine($"Travel Period: {row.TravelPeriod}");
                sb.AppendLine($"Price: {row.Price}");
                sb.AppendLine(new string('-', 50));
            }

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            return outputPath;
        }
    }
}