// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelAgency.Core.Data;

#nullable disable

namespace TravelAgency.Core.Migrations
{
    [DbContext(typeof(TravelAgencyDbContext))]
    [Migration("20260330153041_AddTripPackageUiFields")]
    partial class AddTripPackageUiFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelAgency.Core.Data.Entities.TripPackageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccommodationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer");

                    b.Property<double>("BasePrice")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("ExtraCharges")
                        .HasColumnType("double precision");

                    b.Property<string>("ExtraServices")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MealPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("PricingNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SeasonEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SeasonStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StayType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("VatPercent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TripPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
